freebsd_instance:
  image: freebsd-12-1-release-amd64
  cpu: 1
  memory: 8G

env:
  CIRRUS_CLONE_DEPTH: 1
  GITHUB_TOKEN: ENCRYPTED[ed170fdbb21e31f2f09259d8e5ef007450794ee10d9f3a6387661ecd35d1f9b4d1f6a888d01f3d223e19582328bc6f9f]

task:
  stateful: false
  timeout_in: 60m

  matrix:
    env:
      # We can use up to 8.0 CPUs for FreeBSD in parallel
      # DESKTOP: gnome
      # DESKTOP: kde
      - DESKTOP: lumina
      # DESKTOP: mate
      - DESKTOP: xfce

  install_script:
    - env
    - kldstat
    - kldload zfs.ko
    - kldload tmpfs.ko # Needed?
    - kldload nullfs.ko
    - kldload geom_uzip.ko
    - kldstat
    - pkg install -y pkg git-lite zsync # qemu-devel uefi-edk2-qemu-x86_64
    - mkdir -p /usr/local/furybsd
    - mount -t tmpfs tmpfs /usr/local/furybsd
  
  test_script:
    - /bin/sh -x ./build.sh "${DESKTOP}" || true # FIXME: Why does this return an error even though the ISO succeeded?
    - ls -lh "${CIRRUS_WORKING_DIR}"/*.iso*
    - df -h
    - ( cd "${CIRRUS_WORKING_DIR}" ; zsyncmake *.iso )
    - wget -c "https://raw.githubusercontent.com/probonopd/uploadtool/8142d461aba7b92a058116fe5ee75be438b75fa4/upload.sh"
    - sh upload.sh "${CIRRUS_WORKING_DIR}"/*.iso*

  # only_if: $BRANCH == "master"
