freebsd_instance:
  image: freebsd-12-1-release-amd64
  cpu: 2
  memory: 8G

env:
  CIRRUS_CLONE_DEPTH: 1

task:
  stateful: false
  timeout_in: 120m
  
  install_script:
    - env
    - kldstat
    - kldload zfs.ko
    - kldload tmpfs.ko # Needed?
    - kldload nullfs.ko
    - kldload geom_uzip.ko
    - kldstat
    - pkg install -y pkg git-lite # qemu-devel uefi-edk2-qemu-x86_64
    - mkdir -p /usr/local/furybsd
    - mount -t tmpfs tmpfs /usr/local/furybsd
    
  test_script:
    - /bin/sh -x ./build.sh
    - ls -lh /*.iso*
    - df -h
    
  binaries_artifacts:
    path: "/*.iso*"
