freebsd_instance:
  image: freebsd-12-1-release-amd64
  cpu: 2
  memory: 8G

env:
  CIRRUS_CLONE_DEPTH: 1

task:
  stateful: false
  timeout_in: 120m
  
  install_script:
    - env
    - kldstat
    - kldload zfs.ko
    - kldload tmpfs.ko # Needed?
    - kldload nullfs.ko
    - kldload geom_uzip.ko
    - kldstat
    - pkg install -y pkg git-lite # qemu-devel uefi-edk2-qemu-x86_64
    - mkdir -p /usr/local/furybsd
    # mount -t tmpfs tmpfs /usr/local/furybsd
    # Use compression, https://prodevsblog.com/questions/780666/is-there-an-in-memory-compressed-swap-facility-like-compcache-for-freebsd/
    - mdconfig -a -t malloc -o compress -o reserve -s 6g -u 7
    - newfs -U /dev/md7
    - mount /dev/md7 /usr/local/furybsd
    
  test_script:
    - /bin/sh -x ./build.sh
    - ls -lh /usr/local/furybsd/iso/
    
  binaries_artifacts:
    path: "/usr/local/furybsd/iso/*"
